# Generated by Django 5.2 on 2025-04-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_type', models.CharField(default='Credit Card', max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.JSONField(default=list)),
                ('status', models.IntegerField(choices=[(0, 'Discontinued'), (1, 'Active'), (2, 'Coming Soon')], default=1)),
                ('annual_fee', models.PositiveIntegerField(default=0)),
                ('waiver_on_spend', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_annual_fee', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CashbackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.JSONField(blank=True, null=True)),
                ('spending_type', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_type', models.JSONField(blank=True, null=True)),
                ('payment_app', models.JSONField(blank=True, null=True)),
                ('cashback_percent', models.FloatField(blank=True, null=True)),
                ('monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('min_transaction_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('max_cashback_per_transaction', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_conditions', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_rules', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefits', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percent', models.FloatField()),
                ('monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('min_transaction_amount', models.PositiveIntegerField()),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_cashback', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_income', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.JSONField(blank=True, null=True)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_requirements', models.JSONField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='FeesAndCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('joining_fee_waiver', models.TextField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('cash_advance_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('late_payment_fee', models.JSONField(blank=True, null=True)),
                ('overlimit_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('foreign_transaction_fee', models.FloatField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_and_charges', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_fee', models.PositiveIntegerField()),
                ('waiver_on_annual_spend', models.PositiveIntegerField()),
                ('waiver_description', models.TextField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waiver', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_threshold', models.PositiveIntegerField()),
                ('bonus_type', models.CharField(max_length=50)),
                ('bonus_value', models.IntegerField()),
                ('validity_period', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_bonuses', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='RewardMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('multiplier', models.FloatField()),
                ('monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('min_transaction_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_multipliers', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='RewardPointConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.JSONField()),
                ('min_points_required', models.PositiveIntegerField()),
                ('conversion_description', models.TextField()),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_point_conversion', to='cards.creditcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cards.creditcard')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=255)),
                ('spend_requirement', models.PositiveIntegerField(blank=True, null=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_benefits', to='cards.creditcard')),
            ],
        ),
    ]
