# Generated by Django 5.2 on 2025-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='promotional_card',
            field=models.BooleanField(default=False, help_text='Show this card in the homepage banner'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='promotional_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance in the banner (lower = first)'),
        ),
    ]
