# Generated by Django 5.2 on 2025-04-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_creditcard_promotional_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='apply_url',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='effective_annual_fee',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='network',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='promotional_card',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='promotional_order',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='waiver_on_spend',
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Tailwind or CSS class for color', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend', max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('card_name', models.CharField(max_length=255)),
                ('card_type', models.CharField(default='Credit Card', max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.JSONField(default=list)),
                ('status', models.IntegerField(choices=[(0, 'Discontinued'), (1, 'Active'), (2, 'Coming Soon')], default=1)),
                ('annual_fee', models.PositiveIntegerField(default=0)),
                ('waiver_on_spend', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_annual_fee', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('promotional_card', models.BooleanField(default=False, help_text='Show this card in the homepage banner')),
                ('promotional_order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the banner (lower = first)')),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.bank')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='cards.creditcard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
