# Generated by Django 5.2 on 2025-04-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_creditcard_annual_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='apply_url',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='effective_annual_fee',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='network',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='promotional_card',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='promotional_order',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='status',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='waiver_on_spend',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='annual_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='bank',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='effective_annual_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='network',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='promotional_card',
            field=models.BooleanField(default=False, help_text='Show this card in the homepage banner'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='promotional_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance in the banner (lower = first)'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='status',
            field=models.IntegerField(choices=[(0, 'Discontinued'), (1, 'Active'), (2, 'Coming Soon')], default=1),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='waiver_on_spend',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
