# Generated by Django 5.2 on 2025-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_promotionalbanner_annual_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL to navigate when clicking the banner', max_length=255, null=True),
        ),
    ]
