# Generated by Django 5.2 on 2025-04-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_promotionalbanner_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='cards.creditcard'),
        ),
    ]
