# Generated by Django 5.2 on 2025-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_promotionalbanner_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for the banner', null=True),
        ),
    ]
