# Generated by Django 5.2 on 2025-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_category_creditcard_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CardFilter',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='categories',
            new_name='filters',
        ),
    ]
