# Generated by Django 5.2 on 2025-04-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_rename_category_cardfilter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.JSONField(help_text='Structured highlight data for the card')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='cards.creditcard')),
            ],
        ),
    ]
