# Generated by Django 5.2 on 2025-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='joining_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
