# Generated by Django 5.2 on 2025-04-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_feewaiver_joining_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feewaiver',
            old_name='waiver_on_annual_spend',
            new_name='waiver_on_annual_spends',
        ),
    ]
