# Generated by Django 5.2 on 2025-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_rename_waiver_on_annual_spend_feewaiver_waiver_on_annual_spends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='annual_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='joining_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='waiver_on_annual_spends',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
